# Generated by Django 3.1.3 on 2021-07-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='technology',
        ),
        migrations.AddField(
            model_name='product',
            name='recommendation_type',
            field=models.CharField(blank=True, choices=[('liquids', 'Liquids'), ('solids', 'Solids')], max_length=32, null=True, verbose_name='recommendation type'),
        ),
    ]
