# Generated by Django 3.1.3 on 2021-08-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210729_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='grade'),
        ),
    ]
