# Generated by Django 3.1.3 on 2021-08-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_crop_default_threshold'),
        ('products', '0003_product_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='crops',
            field=models.ManyToManyField(blank=True, to='crops.Crop', verbose_name='crops'),
        ),
    ]
