# Generated by Django 3.1.3 on 2021-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_crops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recommendation_type',
            field=models.CharField(blank=True, choices=[('liquids', 'Liquids'), ('solids', 'Solids')], help_text='For what type of recommendation applies, regardless of the presentation of the product', max_length=32, null=True, verbose_name='recommendation type'),
        ),
    ]
