# Generated by Django 3.1.3 on 2021-08-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_auto_20210802_1506'),
        ('nutrients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrientrequirement',
            name='amount',
        ),
        migrations.AddField(
            model_name='nutrientrequirement',
            name='requirement',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='requirement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nutrientrequirement',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='crops.crop', verbose_name='crop'),
        ),
        migrations.AlterField(
            model_name='nutrientrequirement',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='nutrients.nutrient', verbose_name='nutrient'),
        ),
    ]
