# Generated by Django 3.1.3 on 2021-09-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0003_nutrientconvertionparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrientconvertionparameter',
            name='factor',
            field=models.DecimalField(decimal_places=5, max_digits=8, verbose_name='factor'),
        ),
    ]
