# Generated by Django 3.1.3 on 2021-09-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0004_auto_20210903_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrientrequirement',
            name='not_required_by_the_crop',
            field=models.BooleanField(default=False, verbose_name='not required by the crop'),
        ),
    ]
