# Generated by Django 3.1.3 on 2021-10-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0006_auto_20210928_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
    ]
